# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem 'dotenv'
gem "middleman", "~>3.1.6"

# Syncing with S3
gem 'middleman-sync'

# Minify HTML
gem 'middleman-minify-html'

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Views
gem 'slim'

# Syntax highlighting
gem 'pygments.rb'

# Cross-templating language block fix for Ruby 1.8
platforms :mri_18 do
  gem "ruby18_source_location"
end
